name: Greetings
on: 
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting message
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for opening your first issue in our repository! One of our maintainers will get in touch with you soon.'
        pr-message: 'Thank you for opening your first pull request in our repository! One of our maintainers will get in touch with you soon.'
